"""Added type key to Post model and changed seeds for Post

Revision ID: 7620c7fd023a
Revises: 52ff45b20b45
Create Date: 2023-09-25 17:24:28.165720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7620c7fd023a'
down_revision = '52ff45b20b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_content', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_posts', schema=None) as batch_op:
        batch_op.drop_column('second_content')

    # ### end Alembic commands ###
